### ISSUE TITLE
installation error:  `from pkg_resources import load_entry_point` fails

### ISSUE THREAD

**Issue by paulirish** [ncrocfer/clf#1]
``` sh
sudo pip install clf
Password:
Downloading/unpacking clf
  Downloading clf-0.4.tar.gz
  Running setup.py (path:/private/tmp/pip_build_root/clf/setup.py) egg_info for package clf

Downloading/unpacking Pygments==2.0.2 (from clf)
  Downloading Pygments-2.0.2-py2-none-any.whl (672kB): 672kB downloaded
Downloading/unpacking docopt==0.6.2 (from clf)
  Downloading docopt-0.6.2.tar.gz
  Running setup.py (path:/private/tmp/pip_build_root/docopt/setup.py) egg_info for package docopt

Downloading/unpacking requests==2.5.3 (from clf)
  Downloading requests-2.5.3-py2.py3-none-any.whl (468kB): 468kB downloaded
Installing collected packages: clf, Pygments, docopt, requests
  Running setup.py install for clf

    Installing clf script to /usr/local/bin
  Found existing installation: Pygments 2.0.1
    Uninstalling Pygments:
      Successfully uninstalled Pygments
  Running setup.py install for docopt

  Found existing installation: requests 2.1.0
    Uninstalling requests:
      Successfully uninstalled requests
Successfully installed clf Pygments docopt requests
Cleaning up...
```

...

``` sh
$ clf
Traceback (most recent call last):
  File "/usr/local/bin/clf", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2603, in <module>
    working_set.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 666, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
pkg_resources.DistributionNotFound: requests==2.5.3
```

**Comment by paulirish** [comment]
did this and was all set:
https://pypi.python.org/pypi/setuptools/0.9.8#installation-instructions

you could close or drop a note in the install docs.

**Comment by ncrocfer** [comment]
Thank you for this trick @paulirish, it may be useful to other users :+1:
