### ISSUE TITLE
request version conflict

### ISSUE THREAD

**Issue by coolzilj** [ncrocfer/clf#3]
I have installed httpie which use the same request package but a version greater than 2.3.0,
but clf locks the request version to 2.6.0. 
So everytime I install clf, it will uninstall httpie's 2.7.0 request for me, and install 2.6.0.
I'm sorry to bother you that how can I make httpie and clf friends? 
(I'm from ruby community and not so familiar with python.)

**Comment by jenhsun** [comment]
Same here.

```
$ which clf
/usr/local/bin/clf
$ clf python server
Traceback (most recent call last):
  File "/usr/local/bin/clf", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3074, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3060, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3087, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 647, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 660, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 833, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'requests==2.6.0' distribution was not found and is required by clf
$ sudo pip show requests
---
Metadata-Version: 2.0
Name: requests
Version: 2.7.0
Summary: Python HTTP for Humans.
Home-page: http://python-requests.org
Author: Kenneth Reitz
Author-email: me@kennethreitz.com
License: Apache 2.0
Location: /usr/local/lib/python2.7/site-packages
Requires:
```

By the way, what's the difference between clf and eg? https://github.com/srsudar/eg

**Comment by ncrocfer** [comment]
@coolzilj Thank you for report it, I'll update the dependencies in the next commit.

@jenhsun `Eg` is an advanced `man` command, you can specify a custom Markdown file for each command you want. `Clf` is a command line tool which uses the Commandlinefu.com API and returns some snippets. It's not a man-like tool, it is used to search snippets and one-liners.
