### ISSUE TITLE
clf json

### ISSUE THREAD

**Issue by chocolateboy** [ncrocfer/clf#4]
clf: 0.5.5
python: 2.7.9
OS: Linux (Ubuntu 12.04.5)

```
$ clf json
```

```
Traceback (most recent call last):
  File "~/bin/clf", line 9, in <module>
    load_entry_point('clf==0.5.5', 'console_scripts', 'clf')()
  File "~/opt/python/lib/python2.7/site-packages/clf/__init__.py", line 54, in run
    commands = f.command(arguments['<command>'])
  File "~/opt/python/lib/python2.7/site-packages/clf/api.py", line 107, in command
    commands = self._get(self._prepare_command_url(cmd))
  File "~/opt/python/lib/python2.7/site-packages/clf/api.py", line 90, in _get
    return r.json()
  File "~/opt/python/lib/python2.7/site-packages/requests/models.py", line 819, in json
    return json.loads(self.text, **kwargs)
  File "~/opt/python/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "~/opt/python/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "~/opt/python/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by Xuefeng-Zhu** [comment]
It is the error due to url parse of commandlinefu, since it uses json as part of key word in url scheme.
